### ISSUE TITLE
Broken link in README and in other locations

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/BCBI_base.jl#16]
The README links to https://github.com/brown-data-science/stronghold_environments/blob/master/bcbi_v0.0.0.md

Similarly, the description of the first release links to https://github.com/brown-data-science/stronghold_environments/blob/master/bcbi_v0.0.0.md

Either this repo does not exist, or it is private, because I get a 404 error when I try to access https://github.com/brown-data-science/stronghold_environments

**Comment by mirestrepo** [comment]
I have made it public
