### ISSUE TITLE
Is it worth setting up Travis on this repo?

### ISSUE THREAD

**Issue by DilumAluthge** [bcbi/BCBI_base.jl#3]
There's no code to build, so the Travis build would just resolve and install the packages from REQUIRE - this would make sure that we don't accidentally create a list of dependency requirements that can't be resolved.

**Comment by mirestrepo** [comment]
Seems like a good idea

**Comment by DilumAluthge** [comment]
Actually we probably don't want to install the packages, since that would take a long time. We just need to run Pkg.resolve().

**Comment by DilumAluthge** [comment]
Since the package manager is changing to Pkg3 in julia 1.0, let's wait for 1.0 to be released and then set up .travis.yml and appveyor.yml to run Pkg3.resolve or whatever the appropriate command is.

**Comment by DilumAluthge** [comment]
I'm closing this for now. Once Julia 1.0 is released, let's think about how to approach setting up Travis and/or Appevyor on this repo.
